import { test, expect } from '@playwright/test';
import { createHmac } from 'node:crypto';
import path from 'node:path';
import { loadEnv } from 'vite';

const root = path.resolve('..');
const env = loadEnv('development', root, 'SHIRIN_');
if (env.SHIRIN_ENVIRONMENT !== 'development' || env.SHIRIN_WORK_GROUP_ID !== '0') throw new Error('Browser tests require an isolated demo with notifications disabled');
const built = Boolean(process.env.SHIRIN_BUILT_PREVIEW);
const mini = 'http://localhost:' + (built ? '8093' : '5183');
const admin = 'http://localhost:' + (built ? '8094' : '5184');
function login(uid: number) {
  const values: Record<string, string> = { auth_date: String(Math.floor(Date.now() / 1000)), user: JSON.stringify({ id: uid, first_name: 'Demo' }) };
  const secret = createHmac('sha256', 'WebAppData').update(env.SHIRIN_USER_BOT_TOKEN).digest();
  values.hash = createHmac('sha256', secret).update(Object.keys(values).sort().map(key => key + '=' + values[key]).join('\n')).digest('hex');
  return '#tgWebAppData=' + encodeURIComponent(new URLSearchParams(values).toString());
}

test('mobile mixed cart, selected client, confirmed point, server quote and order', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.route('https://telegram.org/js/telegram-web-app.js', route => route.fulfill({ contentType: 'application/javascript', body: 'window.Telegram={WebApp:{ready(){},expand(){},LocationManager:{isLocationAvailable:true,init(cb){cb()},getLocation(cb){cb({latitude:41.322,longitude:69.283})}}}};' }));
  await page.goto(mini + '/shirin/' + login(202));
  await expect(page.getByRole('heading', { name: 'Хороший вкус. Каждый день.' })).toBeVisible();
  await page.screenshot({ path: '../outputs/mobile-catalog.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: 'Добавить DEMO-001 Ящик', exact: true }).click();
  await page.getByRole('button', { name: '+ DEMO-001 Ящик', exact: true }).click();
  await page.getByRole('button', { name: 'Добавить DEMO-001 Бутылка', exact: true }).click();
  await page.getByRole('button', { name: '+ DEMO-001 Бутылка', exact: true }).click();
  await page.getByRole('button', { name: '+ DEMO-001 Бутылка', exact: true }).click();
  await page.getByRole('link', { name: 'Корзина · 5' }).click();
  await expect(page.getByText('306 000 UZS', { exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Оформить заказ' }).click();
  await page.getByRole('button', { name: /Демо магазин/ }).click();
  await expect(page.getByLabel('Название магазина')).toHaveValue('Демо магазин');
  await expect(page.getByLabel('Телефон', { exact: true })).toHaveValue('+998900000001');
  await page.getByRole('button', { name: 'Моё местоположение' }).click();
  await expect(page.getByLabel('Широта')).toHaveValue('41.311');
  await page.getByRole('button', { name: 'Подтвердить эту точку магазина' }).click();
  await expect(page.getByLabel('Широта')).toHaveValue('41.322');
  await page.getByLabel('Адрес доставки').fill('Ташкент · адрес именно этой доставки');
  await page.getByRole('button', { name: 'Проверить заказ' }).click();
  await expect(page.getByText('306 000 UZS', { exact: true })).toBeVisible();
  await page.screenshot({ path: '../outputs/mobile-checkout.png', fullPage: true, animations: 'disabled' });
  const responsePromise = page.waitForResponse(response => response.url().endsWith('/shirin/api/orders') && response.request().method() === 'POST');
  await page.getByRole('button', { name: 'Подтвердить заказ', exact: true }).click();
  const response = await responsePromise;
  expect(response.status()).toBe(201);
  const order = await response.json();
  expect(order.customer_snapshot.latitude).toBe(41.322);
  expect(order.customer_snapshot.map_url).toContain('69.283%2C41.322');
  expect(order.total_uzs).toBe('306000.00');
  expect(order.customer_snapshot.photo_reference).toBeNull();
  await expect(page.getByRole('heading', { name: 'Заказ принят', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Подробнее', exact: true }).click();
  await page.reload();
  await expect(page.getByRole('heading', { name: order.number })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});

test('admin catalog edit, client archive, Excel preview and access management', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 980 });
  await page.goto(admin + '/shirin/products' + login(101));
  await expect(page.getByRole('heading', { name: 'Товары', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Изменить', exact: true }).first().click();
  await expect(page.getByLabel('Артикул (SKU)')).toBeDisabled();
  await page.getByLabel('Цена ящика, UZS').fill('135000');
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await page.getByRole('button', { name: 'Клиенты', exact: true }).click();
  await page.getByRole('button', { name: 'Добавить клиента', exact: false }).click();
  const clientName = 'Демо клиент ' + Date.now();
  await page.getByLabel('Название магазина').fill(clientName);
  await page.getByLabel('Телефон', { exact: true }).fill('+998900000002');
  await page.getByLabel('Адрес доставки').fill('Тестовый адрес клиента');
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await expect(page.getByText(clientName, { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Excel', exact: true }).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Скачать каталог', exact: false }).click();
  const download = await downloadPromise;
  const filename = await download.path();
  await page.locator('input[type=file]').setInputFiles({ name: 'shirin-catalog.xlsx', mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', buffer: await (await import('node:fs/promises')).readFile(filename!) });
  await expect(page.getByRole('heading', { name: 'Проверка импорта' })).toBeVisible();
  await expect(page.getByText('Без изменений', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Применить', exact: true }).click();
  await expect(page.getByText('Импорт применён', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Доступы', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Доступы', exact: true })).toBeVisible();
  await expect(page.getByLabel('202 Работа с заказами')).toBeChecked();
  await page.getByRole('button', { name: 'Заказы', exact: true }).click();
  await page.screenshot({ path: '../outputs/admin-orders.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: 'RU', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Buyurtmalar', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Buyurtmalar', exact: true })).toBeVisible();
});

test('existing Market superadmin manages Shirin and preserves its root', async ({ page }) => {
  test.skip(!process.env.SHIRIN_MARKET_SMOKE, 'Requires isolated Market backend and panel');
  await page.setViewportSize({ width: 1440, height: 980 });
  const values: Record<string, string> = { auth_date: String(Math.floor(Date.now() / 1000)), user: JSON.stringify({ id: 101, username: 'synthetic' }) };
  const key = createHmac('sha256', 'WebAppData').update('654321:synthetic-market-bot-secret').digest();
  values.hash = createHmac('sha256', key).update(Object.keys(values).sort().map(k => k + '=' + values[k]).join('\n')).digest('hex');
  const hash = '#tgWebAppData=' + encodeURIComponent(new URLSearchParams(values).toString());
  await page.goto('http://localhost:5175/projects/shirin/products' + hash);
  await expect(page.getByRole('heading', { name: 'Товары', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Изменить', exact: true }).first().click();
  await expect(page.getByLabel('Артикул (SKU)')).toBeDisabled();
  await page.getByRole('button', { name: 'Отмена', exact: true }).click();
  await page.getByRole('button', { name: 'Клиенты', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Клиенты', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Доступы', exact: true }).click();
  await expect(page.getByLabel('202 Работа с заказами')).toBeChecked();
  await page.screenshot({ path: '../outputs/market-shirin-integration.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('link', { name: 'Магазины', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Магазины', exact: true })).toBeVisible();
});

test('nested refresh, unavailable geolocation, own draft and API 404', async ({ page, context }) => {
  await page.goto(mini + '/shirin/' + login(303));
  await expect(page.getByRole('heading', { name: 'Хороший вкус. Каждый день.' })).toBeVisible();
  await page.getByRole('button', { name: 'Добавить DEMO-003 Бутылка', exact: true }).click();
  await page.goto(mini + '/shirin/checkout');
  await expect(page.getByLabel('Название магазина')).toHaveValue('');
  await page.getByLabel('Название магазина').fill('Первый черновик');
  const other = await context.newPage();
  await other.goto(mini + '/shirin/checkout');
  await expect(other.getByLabel('Название магазина')).toHaveValue('');
  await expect(page.getByLabel('Название магазина')).toHaveValue('Первый черновик');
  const result = await page.request.get(mini + '/shirin/api/not-found');
  expect(result.status()).toBe(404);
  expect(result.headers()['content-type']).toContain('application/json');
  await page.goto(mini + '/shirin/orders'); await page.reload();
  await expect(page.getByRole('heading', { name: 'Заказы', exact: true })).toBeVisible();
});
