"""Persist Russian and Uzbek bot language

Revision ID: 4dfa111600fd
Revises: 47700e4c3184
Create Date: 2026-10-03 16:39:53.602166

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4dfa111600fd"
down_revision: Union[str, None] = "47700e4c3184"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("language", sa.String(length=2), server_default="ru", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "language")
    # ### end Alembic commands ###
